# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61nimal.proto\x12\x06\x61nimal\"y\n\x06\x41nimal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0e\n\x06\x63\x61geid\x18\x04 \x01(\r\x12\r\n\x05zooid\x18\x05 \x01(\t\x12\x14\n\x0c\x61nimalkindid\x18\x06 \x01(\t\x12\x10\n\x08\x66\x65\x65\x64time\x18\x07 \x01(\t\"z\n\x13\x43reateAnimalRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0e\n\x06\x63\x61geid\x18\x03 \x01(\r\x12\r\n\x05zooid\x18\x04 \x01(\t\x12\x14\n\x0c\x61nimalkindid\x18\x05 \x01(\t\x12\x10\n\x08\x66\x65\x65\x64time\x18\x06 \x01(\t\"6\n\x14\x43reateAnimalResponse\x12\x1e\n\x06\x61nimal\x18\x01 \x01(\x0b\x32\x0e.animal.Animal\"\x86\x01\n\x13UpdateAnimalRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0e\n\x06\x63\x61geid\x18\x04 \x01(\r\x12\r\n\x05zooid\x18\x05 \x01(\t\x12\x14\n\x0c\x61nimalkindid\x18\x06 \x01(\t\x12\x10\n\x08\x66\x65\x65\x64time\x18\x07 \x01(\t\"6\n\x14UpdateAnimalResponse\x12\x1e\n\x06\x61nimal\x18\x01 \x01(\x0b\x32\x0e.animal.Animal\"!\n\x13\x44\x65leteAnimalRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteAnimalResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe4\x01\n\rAnimalService\x12\x45\n\x06\x63reate\x12\x1b.animal.CreateAnimalRequest\x1a\x1c.animal.CreateAnimalResponse\"\x00\x12\x45\n\x06update\x12\x1b.animal.UpdateAnimalRequest\x1a\x1c.animal.UpdateAnimalResponse\"\x00\x12\x45\n\x06\x64\x65lete\x12\x1b.animal.DeleteAnimalRequest\x1a\x1c.animal.DeleteAnimalResponse\"\x00\x42\r\xaa\x02\nGrpcClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'animal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nGrpcClient'
  _globals['_ANIMAL']._serialized_start=24
  _globals['_ANIMAL']._serialized_end=145
  _globals['_CREATEANIMALREQUEST']._serialized_start=147
  _globals['_CREATEANIMALREQUEST']._serialized_end=269
  _globals['_CREATEANIMALRESPONSE']._serialized_start=271
  _globals['_CREATEANIMALRESPONSE']._serialized_end=325
  _globals['_UPDATEANIMALREQUEST']._serialized_start=328
  _globals['_UPDATEANIMALREQUEST']._serialized_end=462
  _globals['_UPDATEANIMALRESPONSE']._serialized_start=464
  _globals['_UPDATEANIMALRESPONSE']._serialized_end=518
  _globals['_DELETEANIMALREQUEST']._serialized_start=520
  _globals['_DELETEANIMALREQUEST']._serialized_end=553
  _globals['_DELETEANIMALRESPONSE']._serialized_start=555
  _globals['_DELETEANIMALRESPONSE']._serialized_end=594
  _globals['_ANIMALSERVICE']._serialized_start=597
  _globals['_ANIMALSERVICE']._serialized_end=825
# @@protoc_insertion_point(module_scope)
