# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07student\"/\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\"3\n\x0cReadAllReply\x12#\n\x07replies\x18\x01 \x03(\x0b\x32\x12.student.ReadReply\"/\n\x0eReadAllRequest\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\r\n\x05limit\x18\x02 \x01(\r\"9\n\x0b\x43reateReply\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\r\"7\n\tReadReply\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\";\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\"\x1e\n\x0bUpdateReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x1e\n\x0b\x44\x65leteReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa8\x02\n\x07Student\x12\x38\n\x06\x63reate\x12\x16.student.CreateRequest\x1a\x14.student.CreateReply\"\x00\x12\x32\n\x04read\x12\x14.student.ReadRequest\x1a\x12.student.ReadReply\"\x00\x12;\n\x07readall\x12\x17.student.ReadAllRequest\x1a\x15.student.ReadAllReply\"\x00\x12\x38\n\x06update\x12\x16.student.UpdateRequest\x1a\x14.student.UpdateReply\"\x00\x12\x38\n\x06\x64\x65lete\x12\x16.student.DeleteRequest\x1a\x14.student.DeleteReply\"\x00\x42\r\xaa\x02\nGrpcClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nGrpcClient'
  _globals['_CREATEREQUEST']._serialized_start=26
  _globals['_CREATEREQUEST']._serialized_end=73
  _globals['_READALLREPLY']._serialized_start=75
  _globals['_READALLREPLY']._serialized_end=126
  _globals['_READALLREQUEST']._serialized_start=128
  _globals['_READALLREQUEST']._serialized_end=175
  _globals['_CREATEREPLY']._serialized_start=177
  _globals['_CREATEREPLY']._serialized_end=234
  _globals['_READREQUEST']._serialized_start=236
  _globals['_READREQUEST']._serialized_end=261
  _globals['_READREPLY']._serialized_start=263
  _globals['_READREPLY']._serialized_end=318
  _globals['_UPDATEREQUEST']._serialized_start=320
  _globals['_UPDATEREQUEST']._serialized_end=379
  _globals['_UPDATEREPLY']._serialized_start=381
  _globals['_UPDATEREPLY']._serialized_end=411
  _globals['_DELETEREQUEST']._serialized_start=413
  _globals['_DELETEREQUEST']._serialized_end=440
  _globals['_DELETEREPLY']._serialized_start=442
  _globals['_DELETEREPLY']._serialized_end=472
  _globals['_STUDENT']._serialized_start=475
  _globals['_STUDENT']._serialized_end=771
# @@protoc_insertion_point(module_scope)
