# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
from pb import grpc

from pb import student_pb2 as student__pb2


class StudentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/student.Student/create',
                request_serializer=student__pb2.CreateRequest.SerializeToString,
                response_deserializer=student__pb2.CreateReply.FromString,
                )
        self.read = channel.unary_unary(
                '/student.Student/read',
                request_serializer=student__pb2.ReadRequest.SerializeToString,
                response_deserializer=student__pb2.ReadReply.FromString,
                )
        self.readall = channel.unary_unary(
                '/student.Student/readall',
                request_serializer=student__pb2.ReadAllRequest.SerializeToString,
                response_deserializer=student__pb2.ReadAllReply.FromString,
                )
        self.update = channel.unary_unary(
                '/student.Student/update',
                request_serializer=student__pb2.UpdateRequest.SerializeToString,
                response_deserializer=student__pb2.UpdateReply.FromString,
                )
        self.delete = channel.unary_unary(
                '/student.Student/delete',
                request_serializer=student__pb2.DeleteRequest.SerializeToString,
                response_deserializer=student__pb2.DeleteReply.FromString,
                )


class StudentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=student__pb2.CreateRequest.FromString,
                    response_serializer=student__pb2.CreateReply.SerializeToString,
            ),
            'read': grpc.unary_unary_rpc_method_handler(
                    servicer.read,
                    request_deserializer=student__pb2.ReadRequest.FromString,
                    response_serializer=student__pb2.ReadReply.SerializeToString,
            ),
            'readall': grpc.unary_unary_rpc_method_handler(
                    servicer.readall,
                    request_deserializer=student__pb2.ReadAllRequest.FromString,
                    response_serializer=student__pb2.ReadAllReply.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=student__pb2.UpdateRequest.FromString,
                    response_serializer=student__pb2.UpdateReply.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=student__pb2.DeleteRequest.FromString,
                    response_serializer=student__pb2.DeleteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'student.Student', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Student(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student.Student/create',
            student__pb2.CreateRequest.SerializeToString,
            student__pb2.CreateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student.Student/read',
            student__pb2.ReadRequest.SerializeToString,
            student__pb2.ReadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student.Student/readall',
            student__pb2.ReadAllRequest.SerializeToString,
            student__pb2.ReadAllReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student.Student/update',
            student__pb2.UpdateRequest.SerializeToString,
            student__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/student.Student/delete',
            student__pb2.DeleteRequest.SerializeToString,
            student__pb2.DeleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
